apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app_label }}
  name: {{ .Values.deployment_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app_label }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.app_label }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.image_name }}
        resources: {}
status: {}
